name: Matchbox
version: '${version}'
main: com.ohacd.matchbox.Matchbox
api-version: '1.21.10'
authors: [ OhACD ]
description: A Minecraft Social Minigame
softdepend: [ ProtocolLib ]

commands:
  matchbox:
    description: Main command for Matchbox game
    usage: /<command> [subcommand] [args]
    aliases: [mb, mbox]
