name: Matchbox
version: '0.8-beta'
main: com.ohacd.matchbox.Matchbox
api-version: '1.21'
authors: [ OhACD ]
description: A Minecraft Social Minigame

commands:
  matchbox:
    description: Main command for Matchbox game
    usage: /<command> [subcommand] [args]
    aliases: [mb, mbox]
